### ISSUE TITLE
Docker (Windows): Ran out of memory for input buffer

### ISSUE THREAD

**Issue by rune3132** [na--/ebook-tools#3]
Here is a screenshot of the entire error message, it happens when processing seemingly random books (It has only happened thrice while processing around 50.000 books). It creates a folder named ERROR at 35 in the output folder while crashing.
![image](https://user-images.githubusercontent.com/12607046/32985985-44417dc0-ccc7-11e7-9918-bf41948a0140.png)

**Comment by na--** [comment]
Thanks for the bug report! You've actually found two separate bugs here - the xml parser error and the creation of that folder :) I managed to reproduce both of them. The folder issue was easily fixed, but the other issue seems to be due to a bug in `libxml-xpath-perl` when parsing some xml files with large elements. I think that the only solution will be to use another tool for xpath, I'll try to fix it in a few days.

**Comment by na--** [comment]
@rune3132, can you please verify that the issue was fixed in the latest version? 

btw in my testing I noticed that there was a third bug with the same code... :) Books with titles that had `&` in the name were renamed to `something &amp; something` - the xml entities were left in the new filenames. This should be fixed as well.

**Comment by rune3132** [comment]
It appears to be fixed, but that might be because I've already run all my books through your program. I would like to add that this is an amazing program that you have created. I especially love how fast it is to make Calibres terrible naming scheme a lot less aids. Very nice.
